name: Deploy Node.js Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build (if needed)
        run: npm run build # Remove if not required

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            REPO_DIR="/home/ubuntu/projects/${{ github.repository }}"
            if [ ! -d "$REPO_DIR" ]; then
              mkdir -p "$REPO_DIR"
              cd "$REPO_DIR"
              git clone https://github.com/${{ github.repository }}.git .
            else
              cd "$REPO_DIR"
              git fetch origin
              git reset --hard origin/main
            fi
            echo "${{ secrets.ENV_FILE }}" > .env
            npm install
            npm run build
            pm2 stop my-app || true
            pm2 start npm --name "my-app" -- start
